spring:
  thymeleaf:
    cache: false # 타임리프 캐시 끄기
    prefix: file:src/main/resources/templates/
  devtools:
    livereload:
      enabled: true
      restart:
        enabled: true

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/basic1__dev?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: lldj
    password: lldj1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create # DB 테이블 자동생성
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  profiles:
    active: dev # dev 환경임을 표시